* 命中
   RogueTech里的基础命中为80%,实际命中通过多种效果对基础命中进行修饰得出
   命中修饰符正为减益
   1) 修饰符:
      * 机甲运动:
        + 移动 +1
        + 冲刺 +2(和移动叠加)
        + 跳跃 +3(和移动叠加)
      * 目标移动,每个闪避点+2
      * 高差,目标每高一个级别+1,每低一个级别-1
      * 目标角度:
        + 侧面 -1
        + 后面 -2
      * 可见度:
        + 被阻挡 +1
        + 无目视 +5(和被阻挡叠加)
      * 射程
        + 最低射程:+8
        + 近程:0
        + 中程:+2
        + 远程:+4
        + 极远射程:+6
      * 射击模式 间接+2
      * 传感器
        + 无传感器: +5
        + ECM防护: 每点+0.6
      * 驾驶员技能
        + 射击学:每点+1%
        + 谨慎:+1
   2) 射程
      武器信息上列出了3个射程范围最小射程,最佳射程,最大射程
      所有低于最小射程的攻击都会受到+8惩罚,
      近程和中程在最小射程和最佳射程之间,远程和极远射程在最佳和最大射程之间.
      武器伤害衰减在超出最佳射程外开始计算,并在射程极限达到最大
   3) 闪避点
      默认情况下,每台机甲最多可以从移动中获得6点闪避.上限可以通过驾驶员技能和装备来增加.
      在机甲库耐久值上悬停可以获得不计算装备和驾驶员技能的当前可获得的最大闪避点数
      移动距离和闪避点对应
      | 30m | 80m | 140m | 210m | 280m | 330m | 390m | 450m | 510m | 570m | 630m | 690m | 900m | 960m | 990m |
      |   1 |   2 |    3 |    4 |    5 |    6 |    7 |    8 |    9 |   10 |   11 |   12 |   13 |   14 |   15 |
           
* 卡壳
   
** 卡壳机率计算
   每个武器单独计算卡壳机率
   基础机率为武器、弹药和射击模式的卡壳机率的总和.每次武器受到致命损伤都会增加10%卡壳机率.射击学技能每增加1,降低1%卡壳机率
   幸运特性(-10%)、防卡壳火控系统(-25%)、主动瞄准电脑火控系统(-10%)、主动瞄准电脑火控系统(-20%)和受控攻击(-20%)当被与基本机率相乘
   例如:一名驾驶员去射击学为8,幸运,受控爆发技能激活,RAC/5射击3发子弹(5%卡壳机率/发),受到一次致命损伤,使用PRE弹药(4%卡壳)机率
   则卡壳机率=(5%*3[发射数] + 4%[弹药] + 10%[严重损伤] - 7%[射击学]) * 0.9[幸运] * 0.8[受控连射] = 15.84%卡壳机率

** 基于后座的卡壳
   这是一种少见的机制,AC/10 BB5X和BFG 9000等武器含有该机制,该机制和核心卡壳机制是相互独立的
   武器开火后,干扰机率为,其重射修正倍率*卡壳机率,当该卡壳检定确定后还需以驾驶员射击学技能进行d9+2的投骰,当两次等确定卡壳时,武器才会卡壳.
   卡壳机率由 wr-jam_chance_multipiler-x确定,X是机率
   
** 卡壳故障排除
   武器不会随时间而自动解决卡壳,而是每回合根据射击学技能进行检定.如果你非常不幸,整个过程中,你都可能无法排除卡壳故障.
   1到10的随机数字与射击学技能比较,若随机值低于射击学则解除卡壳.
   
* 致命损伤/暴击/致命一击

** 普通致命损伤
   致命损伤机率为=1 - 当前结构值/最大结构值
   致命损伤机率不会低于56%,任何低于该值都会提升到该值
   如果部位装甲已经打光,则每次结构被击中都会触发一次致命损伤投骰.
   
** TAC
   穿甲致命损伤
   受攻击机甲命中部位有100/200装甲,结构完整.
   基础最小致命损伤机率为0.1
   武器有如下属性
   APArmorShardsMod = 0.5 装甲破片率
   PMaxArmorThickness = 150 最大穿深
   APCritChance = 0.5 穿甲致命损伤率
   破片修正 = 1 + (1 - 100/200) = 1.5
   穿深修正 = 1- 100/150 = 0.333

   0.1(最小基础值) * 1.5(破片修正) * 0.333(穿深修正) * 0.5(武器致命损伤率) = 0.025
   当装甲过低时,破片修正和传深修正都对增加.更容易发生TAC
   如有致命损伤率+25%的修饰词条,它们会根据物品进行相加或相乘,最后乘以上面的概率
   0.025*(1 + 25%) = 0.03125
   
* 热效应
   原版的过热效果已被放弃,现已不会在过热情况下直接伤害结构,而是加入了一些随过热程度提高概率的负面效果
   主要影响以下几方面:
   1. 影响命中率
   2. 降低引擎功率,即移动惩罚
   3. 进行d100的停机投骰,失败强制关机
   4. 进行d100的弹药爆炸投骰,失败弹药爆炸
   5. 进行d100的驾驶员受伤投骰,失败驾驶员健康-1
   6. 进行d100的故障投骰,失败时随机组件损坏
   有0到150个热量等级,在同一热量等级下可能产生多种影响,如同时单位停机,弹药爆炸,驾驶员受伤.
   除移动和攻击惩罚外,所有效果会在回合结束时生效.
   多于1点的勇气技能点数,每点会降低5%负面效果概率.

   如勇气技能为3点,机甲在51热量等级下关机机率为10%
   则51热量等级下永远不会关机10%-(3-1)*5% = 0
   具体信息可以将鼠标悬浮在左下角热量条上查看
   
** 热阈值
   热阈值指示器(过热条),原版会受到过热伤害,现在游戏热阈值被固定在42
   RT中对热阈值的描述有不同含义:
   1. 热阈值百分比,例如紧凑型激进散热套件,在超过90%热量时激活,在低于50%热量时停用,是指阈值的百分比
   2. 对过热机甲造成额外伤害的武器,如喷火器,在当前热量超过此阈值时会造成额外伤害.阈值不随驾驶员勇气技能和机甲装备改变.
   3. 某些设备如增强成像(EI)过热时会驾驶员造成伤害,会与热效应中负面作用的驾驶员受伤同时生效,该效果超过阈值即产生,不手勇气技能影响
   4. 驾驶员勇气技能会推迟负面效果产生的热量起始值.
   
** 散热量计算
   机甲基础总散热量=(引擎集成散热器数+引擎附加散热器数+外部装备散热器数) * 散热器散热值
   散热器散热值和可装配的散热器种类由引擎安装的散热套件决定,更换散热套件后外部散热器也必须更换.
   普通单层散热器散热量为3,双层散热器为6
   引擎集成散热器数由引擎核心决定,其数量由引擎核心110的4个到引擎核心500的10个不等,,
   引擎附加散热器容量最大值由引擎核心决定,负数为最少必须安装该数目的外部散热器,且无法安装引擎附加散热器,否则提示组件安装错误,附加散热器有+1到+10几个等级,每+1代表一个额外引擎散热器,根据实际安装的组件计算,但不能超过引擎最大附加容量.

   例子:如安装引擎核心200,集成散热器数量为8,安装的附加散热器容量为0,额外需要2个外部散热器(必须装至少两个外部散热器,否则会提示错误组件)
        安装双层散热套件
        则散热量为 = (8 + 0 + 2) * 6 = 60

        若使用引擎核心320,集成散热器数量为10,可安装附加引擎散热器的容量为2(可安装+1或+2的附加散热器)
        使用单层散热器
        安装+1的附加引擎散热器,不装配外部引擎散热器
        则散热量 = (10 + 1 + 0) * 3 = 33
   
* 电子战
+ ECM可以干扰敌人,保护敌人免受敌人的干扰,并且为携带者提供ECM防护
+ 电战套件降低敌人的ECM防护,并给范围内盟友提供ECM防护
+ 干扰降低攻击者的精度,每点干扰降低0.8精度,最大到无传感器信号-5
+ ECM防护降低攻击者的精度,每点防护降低0.6精度,最大到无传感器信号-5
+ 隐身系统降低单位的可见度和信号特征,还给攻击者提供额外惩罚
+ C3系统使用组合范围
  + 给范围内敌人debuff
    * 更容易通过视觉或传感器侦测
    * 被动地给范围内敌人添加一个或多个传感器PING.每个传感器PING点都会使防护/隐身效果-1
  + 给友军增益
    * 盟友获得视觉和传感器范围增
+ 主动探测器可以增加单位的视觉或传感器范围,检测雷区,并抵消隐身或ECM防护的影响.
+ 效果可以叠加.两个+10%传感器范围的来源总共提供+21%的传感器范围.两个+2的干扰源,总共提供+4干扰

所有电子战效果最后都作用到4个数值上:
1) 传感器侦测范围
   范围受3个因素影响:
   1. 基础传感器范围
      * 机甲:16格*25m=400m
      * 载具:12格*25m=350m
      * 炮塔:20格*25m=500m
      * 其他:12格*25m=300m
      传感器范围不会低于5格*25=125m
   2. EWC,每回合都会重新计算
      1. 如果单位安装了AR14信标,提供了+15%范围加成
         则对于机甲来说传感器范围400*(1+15%)=460m
      2. 传感器投骰修正
         每回合都会在-14和+14间随机,随机值/10对范围进行再修正
         如本回合获得+3,则修正倍率为1+3/10=1.3,若是-2则为1-2/10=0.8
         例如本回合投骰修正为1,则传感器范围为460*(1+1/10)=460*1.1=506m 
   3. 目标信号特征强度
      目标信号特征强度会受如隐身装甲或C3效果影响,如果目标刚刚开火,则在一段时间内会增加信号特征,连续开火会堆叠
      地形也会影响特征强度,森林信号特征*0.8,水中特征强度*1.2
      无源探测器,有些无源探测器提供了-25%信号特征的效果
      此时探测范围为506m*(1-25%)=379.5m
2) 视觉侦测范围
   计算方法与传感器类似
   敌人有三种状态:
   + 可见:目标在可视范围内,并且有视线(LoS)
   + 无视觉:目标存在LoS,但目标超出了可视范围,不时攻击会受到+5无视觉惩罚
   + 无LoS:目标不可视,无法直瞄射击

   可视范围受以下状态影响:
   + 一天内的时间
     定义了基本可视范围:
     + 明亮:48格*25m=1200m
     + 昏暗:24格*25m=600m
     + 黑暗:12格*25m=300m
   + 天气
     天气会对基本可视范围进行修饰,如雨雪轻雾天气*0.8,浓雾*0.7等
   + 装备
     座舱,传感器,主动探测器会影响范围

   示例:
        配备主动探测器和测距仪++的单位在昏暗雨天
        (600(昏暗) + 60(测距仪++)) * 0.8雨 * 1.1(主动探测器) = 581m(23格)
     
3) 传感器信息
   一个传感器检测的最基础信息是目标位置,除此之外驾驶员还可以通过传感器获得目标名称,装甲值,装备等内容
4) 攻击精度
   每点精度,大概影响2-7%的命中率

** 基本电子战效果
   * 防御效果
     1) 屏蔽效果
        大多数屏蔽效果只适用于携带装置的单位.
        最基本的效果为ECM防护.这代表了多光谱设备,混淆了敌人的制导系统,影响敌人的瞄准计算机
        最高ECM防护和干扰惩罚合计为5点(传感器没检测到),无论ECM屏蔽和干扰有多大,最高合计5点
        ECM屏蔽还会将屏蔽单位的信号特征降低-10%,并让对被屏蔽单位的信息检查处以+1的惩罚(获取的信息更粗略)
        ECM屏蔽效果可以通过传感器PING和主动探测器来减弱或抵消
     2) 干扰效果
        干扰和屏蔽效果类似,只是作用于敌人而不是友军.干扰效果会干扰范围内所有敌人(除非有特殊说明否则不会干扰友军),通过将ECM切换为主动模式产生干扰而不是屏蔽,受干扰的敌人无论对谁攻击都会受到每干扰点0.8精度的惩罚.
     3) 隐身
        隐身有两种方式信号隐身和视觉隐身
   * 攻击效果
     1) 传感器
        最基本的电子战设备是任何机甲都内置的传感器
        它们一般为会对传感器或视觉范围提供增益,同时让获取的敌人信息更详细
     2) 主动探测器
        以猎兔犬探测器为例
        * +10%传感器范围,多个传感器范围修正都以乘法方式应用
        * +10%视野范围,多个视野范围修正都以乘法方式应用
        * 被动探测器,-2点EMC/隐身,当对受ECM或隐身效果保护的敌人攻击时,敌人ECM防护/隐身效果点数-2
          例如:敌人装备守护者ECM,获得4点ECM屏蔽,本来精度损失为4*0.6=2.4,当装备猎兔犬后精度损失为(4-2)*0.6=1.2
        * 传感器信息奖励+2,获取信息更详细
        * 检测90米范围内的雷区,会在白色圈范围内含有地雷的地面标上三角警告标志
          
     3) 抗干扰
        ECM可以工作在被动(屏蔽)和主动(干扰)模式两种模式下,还有抗干扰功能,
        如天使ECM其干扰光环强度为5,会造成4(5*0.8)点精度惩罚
        如果机甲配备了被动模式的守护者ECM,可以减少3点干扰,则天使ECM的实际干扰点为2(5-3)点既只受到2*0.8=1.6精度惩罚

     4) 传感器锁定
        传感器锁定(无人机或战术能力提供)会对锁定单位的隐身和ECM提供实质性debuff
        处移除闪避点外,在回合结束前还有以下效果:
        1. EMC屏蔽-6
        2. 隐身点数-6
        3. 传感器信号特征+100%
        4. 视觉特征+100%
     5) C3网络
        现在有实际网络,文档未更新,基本上效果为增加传感器/视野范围,削减ECM/隐身层数
     6) TAG
        目标寻获装备,与其他加成叠加,但不与其他TAG叠加.
        TAG为电子战提供增益,使目标更容易被侦测和获取信息,TAG奖励会随着目标移动而衰减,如果目标不移动,则不衰减.
        TAG还增加了目标的的传感器和视觉特征强度     
** 隐身
   隐身有两种,传感器隐身和视觉隐身,需要运行某种隐身ECM
   任何一种隐身都是隐身装甲的固有属性,通常一种隐身装甲只有一种隐身效果,但可以通过附加模块(必须配合合适的隐身装甲)

